# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SELENIUM_GRID_URL=http://selenium:4444/wd/hub
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://db:5432/apartment-tracker
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      selenium:
        condition: service_started
      db:
        condition: service_healthy
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=apartment-tracker
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

